# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=200, verbose_name='申请单号')),
                ('department', models.CharField(max_length=200, verbose_name='申请部门')),
                ('applicant', models.CharField(max_length=200, verbose_name='需求人员')),
                ('operator', models.CharField(default='', max_length=200, verbose_name='操作人员')),
                ('inspector', models.CharField(default='', max_length=200, verbose_name='检查人员')),
                ('urgent', models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=6, verbose_name='优先级别')),
                ('schedule_time', models.DateTimeField(default='', verbose_name='计划时间')),
                ('configuration_type', models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='配置类型')),
                ('resource_verification', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='资源核查')),
                ('impact_assessment', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='影响评估')),
                ('change_plan', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='变更方案')),
                ('configuration_check', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='配置检查')),
                ('scripting', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='脚本编写')),
                ('emergency_plan', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='应急方案')),
                ('fallback_scheme', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='回退方案')),
                ('cceptance_plan', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='验收方案')),
                ('note', models.TextField(verbose_name='详细描述')),
                ('device_address', models.CharField(max_length=200, verbose_name='设备地址')),
                ('configuration_script', models.FileField(upload_to='./upload/', verbose_name='配置脚本')),
                ('change_preparation_confirmation', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='准备确认')),
                ('change_process_validation', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='流程确认')),
                ('change_operation_confirmation', models.CharField(choices=[('1', '已核实'), ('2', '核实中'), ('3', '未核实')], max_length=6, verbose_name='操作确认')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '配置申请',
                'verbose_name_plural': '配置申请',
            },
        ),
    ]
