# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationrequisition',
            old_name='cceptance_plan',
            new_name='acceptance_plan',
        ),
    ]
