# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationrequisition',
            options={'verbose_name': '配置申请', 'verbose_name_plural': '配置申请'},
        ),
        migrations.AddField(
            model_name='configurationrequisition',
            name='inspector',
            field=models.CharField(default=1, max_length=200, verbose_name='检查人员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configurationrequisition',
            name='operator',
            field=models.CharField(default=1, max_length=200, verbose_name='操作人员'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='change_operation_confirmation',
            field=models.BooleanField(default=False, verbose_name='操作确认'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='change_preparation_confirmation',
            field=models.BooleanField(default=False, verbose_name='准备确认'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='change_process_validation',
            field=models.BooleanField(default=False, verbose_name='流程确认'),
        ),
    ]
