# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netop', '0002_auto_20171031_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationrequisition',
            name='device_address',
            field=models.GenericIPAddressField(verbose_name='设备地址'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='schedule_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='计划时间'),
        ),
    ]
