# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netop', '0003_auto_20171031_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationrequisition',
            name='publish',
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='acceptance_plan',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='验收方案'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='application_number',
            field=models.CharField(help_text='are you ok?', max_length=200, verbose_name='申请单号'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='change_operation_confirmation',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='操作确认'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='change_plan',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='变更方案'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='change_preparation_confirmation',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='准备确认'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='change_process_validation',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='流程确认'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='configuration_check',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='配置检查'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='emergency_plan',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='应急方案'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='fallback_scheme',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='回退方案'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='impact_assessment',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='影响评估'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='note',
            field=models.TextField(verbose_name='其它备忘'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='resource_verification',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='资源核查'),
        ),
        migrations.AlterField(
            model_name='configurationrequisition',
            name='scripting',
            field=models.CharField(choices=[('1', '新增'), ('2', '修改'), ('3', '删除')], max_length=6, verbose_name='脚本编写'),
        ),
    ]
