# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-17 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netop', '0002_auto_20171027_1720'),
        ('netop', '0005_auto_20171101_1604'),
    ]

    operations = [
    ]
